### ISSUE TITLE
''Syntax Error Unexpected token'' error on various .c.o files in Font folder

### ISSUE THREAD

**Issue by fhteagle** [lovyan03/LovyanGFX#603] opened 2024-08-18 14:13 UTC
Greetings and thank you for this project. Trying to build example code for an off the shelf devkit with touchscreen that I want to use as the core of a custom smartwatch. My code skills are somewhere between "really rusty" and "nonexistant", so pardon me if this is the result of something silly and obvious.

## Environment 

- MCU or Board name:  ESP32-S3-DevKitC-1-N8 in ([Waveshare devkit with 1.69 display](https://www.waveshare.com/ESP32-S3-Touch-LCD-1.69.htm))
- Panel Driver IC:    ST7789  (physical part is ST7789V2) 
- Bus type:           SPI
- LovyanGFX version:  1.1.6
- FrameWork version:  espressif32 
- Build Environment:   PlatformIO 6.1.5 in codium 1.92.2
- Operating System:   Arch Linux x86_64

## Problem Description ( 問題の内容 )

During build, one of many .c files in sub-folders of the Font folder does not output to .c.o correctly, with ``` Syntax Error Unexpected Token near '(' ``` thrown in terminal.

### Expected Behavior ( 期待される動作 )

Compile without syntax errors

### Actual Behavior ( 実際の動作 )

Compile error on a random one of many .c.o files from Font folder

### Steps to reproduce ( 再現のための前提条件 )

0. Following horribly written tutorial at https://www.waveshare.com/wiki/ESP32-S3-Touch-LCD-1.69, starting from "ESP32-S3-Touch-LCD-1.69 Watch Project" section
1. Install and configure codium (open source version of VSCode), and within that install platformio extension
2. git clone https://github.com/fbiego/esp32-c3-mini
3. Uncomment line 17 define environment to lolin_s3_mini_1_69 in platformio.ini, comment out other lines in that block
4. Click build (check mark icon in bottom toolbar)
5. Note build failure with errors, example at (https://pastebin.com/zwPATPy5)
6. Try cleaning the build, click build again, same results

Not including complete source code, as I have not modified any code from that checked out from git source given above + modules automatically pulled in by platform.io

**Comment by tobozo** [comment] 2024-08-18 14:21
hi,

`sh` is complaining, so the problem is with vscodium configuration, not with LovyanGFX.

my guess is it has something to do with the `<myuser>` part in the pastebin logs (maybe some json file needed to be updated with the homedir path somewhere along the installation ?)

I suggest you investigate the "Install and configure codium" part

closing this as not a bug

**Closed by tobozo** 2024-08-18 14:21 UTC
